#!/bin/bash
# Complete installation script for all dependencies
set -e  # Exit on error

echo "Installing dependencies for Microbiome Sequencing Simulator..."
WORK_DIR=$(pwd)
LOG_FILE="$WORK_DIR/installation.log"

# Initialize log file
echo "Installation Log - $(date)" > "$LOG_FILE"

# Log function
log() {
    echo "$1"
    echo "$(date): $1" >> "$LOG_FILE"
}

# Error handling
handle_error() {
    log "ERROR: $1"
    exit 1
}

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

#=====================
# Check for conda
#=====================
if ! command_exists conda; then
    log "Conda not found. Please install Miniconda or Anaconda first."
    log "Visit https://docs.conda.io/en/latest/miniconda.html for installation instructions."
    exit 1
fi

#=====================
# Create conda environment
#=====================
ENV_NAME="mhass"
log "Creating conda environment: $ENV_NAME"

# Check if environment already exists
if conda env list | grep -q "^$ENV_NAME "; then
    log "Environment $ENV_NAME already exists."
    read -p "Do you want to update it? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log "Installation aborted by user."
        exit 0
    fi
    
    conda env update -n $ENV_NAME -f environment.yml
else
    # Create environment.yml file
    cat > environment.yml << 'EOF'
name: mhass
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.6
  - r-base>=4.0
  - r-optparse
  - bioconductor-biostrings
  - r-remotes
  - pbsim3
  - pbccs
  - tqdm>=4.50.0
  - pip
  - setuptools>=42
  - wheel
EOF
    
    # Create the conda environment
    conda env create -f environment.yml
    if [ $? -ne 0 ]; then
        handle_error "Failed to create conda environment"
    fi
fi

log "Conda environment '$ENV_NAME' is ready."
conda activate $ENV_NAME

#=====================
# Install metaSPARSim in the conda environment
#=====================
log "Installing metaSPARSim R package..."
conda run -n $ENV_NAME Rscript -e '
if (!requireNamespace("metaSPARSim", quietly = TRUE)) {
  if (!requireNamespace("remotes", quietly = TRUE)) {
    install.packages("remotes", repos = "https://cloud.r-project.org/")
  }
  
  tryCatch({
    remotes::install_gitlab("sysbiobig/metaSPARSim")
  }, error = function(e) {
    tryCatch({
      remotes::install_git("https://gitlab.com/sysbiobig/metasparsim.git")
    }, error = function(e2) {
      message("Failed to install metaSPARSim. Will try again at runtime.")
    })
  })
}
'

#=====================
# Install the package
#=====================
log "Installing mhass package..."
conda run -n $ENV_NAME pip install -e .

#=====================
# Create resource directories and install PBSIM if needed
#=====================
mkdir -p mhass/resources/pbsim3/src
mkdir -p mhass/resources/pbsim3/data

# Copy the PBSIM executable and model if available in conda environment
PBSIM_PATH=$(conda run -n $ENV_NAME which pbsim 2>/dev/null || echo "")
if [ -n "$PBSIM_PATH" ]; then
    log "Found PBSIM at: $PBSIM_PATH"
    cp "$PBSIM_PATH" mhass/resources/pbsim3/src/pbsim
    
    # Try to find QSHMM model
    CONDA_ENV_PATH=$(dirname $(dirname "$PBSIM_PATH"))
    QSHMM_PATHS=(
        "$CONDA_ENV_PATH/share/pbsim3/data/QSHMM-RSII.model"
        "$CONDA_ENV_PATH/lib/pbsim3/data/QSHMM-RSII.model"
    )
    
    for QSHMM_PATH in "${QSHMM_PATHS[@]}"; do
        if [ -f "$QSHMM_PATH" ]; then
            log "Found QSHMM model at: $QSHMM_PATH"
            cp "$QSHMM_PATH" mhass/resources/pbsim3/data/
            break
        fi
    done
else
    log "PBSIM not found in conda environment. Will build from source."
    
    # Clone and build PBSIM3
    temp_dir=$(mktemp -d)
    cd "$temp_dir"
    
    git clone https://github.com/yukiteruono/pbsim3.git
    cd pbsim3
    ./configure
    make
    
    if [ -f "src/pbsim" ]; then
        log "PBSIM3 built successfully."
        cp src/pbsim "$WORK_DIR/mhass/resources/pbsim3/src/"
        cp data/QSHMM-RSII.model "$WORK_DIR/mhass/resources/pbsim3/data/"
    else
        handle_error "PBSIM3 build failed"
    fi
    
    # Clean up
    cd "$WORK_DIR"
    rm -rf "$temp_dir"
fi

#=====================
# Create default resource files
#=====================
log "Creating default resource files..."

# Create default barcode file
cat > mhass/resources/barcodes.txt << 'EOF'
A1	GGTTATGCGGTTCACTGCCACATATCAGAGTGCG	CGTCACTTGGCGTATTGGCGTCTCTATCTCTCTA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A2	GGTTATGCGGTTCACTGCCTGTGTGCTCGCTATG	CGTCACTTGGCGTATTGGAGCGTCTGACGTGAGT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A3	GGTTATGCGGTTCACTGCACACATCTCGTGAGAG	CGTCACTTGGCGTATTGGTCTACTACACTGTACT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A4	GGTTATGCGGTTCACTGCCACGCACACACGCGCG	CGTCACTTGGCGTATTGGTCTATGTCTCAGTAGT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A5	GGTTATGCGGTTCACTGCCACTCGACTCTCGCGT	CGTCACTTGGCGTATTGGATAGCGACGCGATATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A6	GGTTATGCGGTTCACTGCCATATATATCAGCTGT	CGTCACTTGGCGTATTGGTCTCTCGATATGATAG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A7	GGTTATGCGGTTCACTGCTCTGTATCTCTATGTG	CGTCACTTGGCGTATTGGTATACACACTCGCTCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A8	GGTTATGCGGTTCACTGCACAGTCGAGCGCTGCG	CGTCACTTGGCGTATTGGATATGAGTGACTCGTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A9	GGTTATGCGGTTCACTGCGTGTGAGATATATATC	CGTCACTTGGCGTATTGGGTCTCTCTCTCACGCA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A10	GGTTATGCGGTTCACTGCACGCGCTATCTCAGAG	CGTCACTTGGCGTATTGGCACGACTATATGCTCT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A11	GGTTATGCGGTTCACTGCCTATACGTATATCTAT	CGTCACTTGGCGTATTGGTAGAGCGTGCATATAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
A12	GGTTATGCGGTTCACTGCACACTAGATCGCGTGT	CGTCACTTGGCGTATTGGACGACGCGCACTGACA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B1	GGTTATGCGGTTCACTGCGTCGCGCATAGAGCGC	CGTCACTTGGCGTATTGGGTCTATCTCGCGAGAG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B2	GGTTATGCGGTTCACTGCCGTGTCACTCTGCGTG	CGTCACTTGGCGTATTGGGACAGCATCTGCGCTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B3	GGTTATGCGGTTCACTGCCGCATGACACGTGTGT	CGTCACTTGGCGTATTGGTGAGATATGCATGATG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B4	GGTTATGCGGTTCACTGCCATAGAGAGATAGTAT	CGTCACTTGGCGTATTGGGTGCGCTACAGTCTCT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B5	GGTTATGCGGTTCACTGCCACACGCGCGCTATAT	CGTCACTTGGCGTATTGGTCACTGTGTGTGTCTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B6	GGTTATGCGGTTCACTGCTCTCACGAGAGCGCAC	CGTCACTTGGCGTATTGGACTCGCGCACGCGCGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B7	GGTTATGCGGTTCACTGCACACACTCTATCAGAT	CGTCACTTGGCGTATTGGAGATATCATCAGCGAG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B8	GGTTATGCGGTTCACTGCCACGACACGACGATGT	CGTCACTTGGCGTATTGGTGCTGCGAGCGCTCTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B9	GGTTATGCGGTTCACTGCCTATACATAGTGATGT	CGTCACTTGGCGTATTGGGTGCATACATACATAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B10	GGTTATGCGGTTCACTGCCACTCACGTGTGATAT	CGTCACTTGGCGTATTGGAGATACACATGATACT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B11	GGTTATGCGGTTCACTGCCAGAGAGATATCTCTG	CGTCACTTGGCGTATTGGTCACATATGTATACAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
B12	GGTTATGCGGTTCACTGCCATGTAGAGCAGAGAG	CGTCACTTGGCGTATTGGCACTATACACTGCGCT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C1	GGTTATGCGGTTCACTGCCGCGACACGCTCGCGC	CGTCACTTGGCGTATTGGCGCTCTGTCACGTCTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C2	GGTTATGCGGTTCACTGCCACAGAGACACGCACA	CGTCACTTGGCGTATTGGGCAGACTCTCACACGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C3	GGTTATGCGGTTCACTGCCTCACACTCTCTCACA	CGTCACTTGGCGTATTGGCACATACTACTACTGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C4	GGTTATGCGGTTCACTGCCTCTGCTCTGACTCTC	CGTCACTTGGCGTATTGGTACTCACTGCGCTCAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C5	GGTTATGCGGTTCACTGCTATATATGTCTATAGA	CGTCACTTGGCGTATTGGGATGTGTGCGCAGTGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C6	GGTTATGCGGTTCACTGCTCTCTCTATCGCGCTC	CGTCACTTGGCGTATTGGGTGTATCAGCGAGTAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C7	GGTTATGCGGTTCACTGCGATGTCTGAGTGTGTG	CGTCACTTGGCGTATTGGGTCTACGCTCGTCGCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C8	GGTTATGCGGTTCACTGCGAGACTAGAGATAGTG	CGTCACTTGGCGTATTGGTATACGAGATACGTGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C9	GGTTATGCGGTTCACTGCTCTCGTCGCAGTCTCT	CGTCACTTGGCGTATTGGCGCGTATGTATGTCGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C10	GGTTATGCGGTTCACTGCATGTGTATATAGATAT	CGTCACTTGGCGTATTGGCGTCTATATACGTATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C11	GGTTATGCGGTTCACTGCGCGCGCGCACTCTCTG	CGTCACTTGGCGTATTGGGCGCGTGCTGCGTCTA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
C12	GGTTATGCGGTTCACTGCGAGACACGTCGCACAC	CGTCACTTGGCGTATTGGCGCGCTCAGCTGATCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D1	GGTTATGCGGTTCACTGCACACATATCGCACTAC	CGTCACTTGGCGTATTGGGCTCGACTGTGAGAGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D2	GGTTATGCGGTTCACTGCGTGTGTCTCGATGCGC	CGTCACTTGGCGTATTGGACAGAGTGTGCAGATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D3	GGTTATGCGGTTCACTGCCGCACACATAGATACA	CGTCACTTGGCGTATTGGCGCACAGATACGCTCT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D4	GGTTATGCGGTTCACTGCTGTCATATGAGAGTGT	CGTCACTTGGCGTATTGGTATGACTAGTGTACTA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D5	GGTTATGCGGTTCACTGCTCTCGCGCGTGCACGC	CGTCACTTGGCGTATTGGATACACTCATGTGCAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D6	GGTTATGCGGTTCACTGCCTCGCTCGACGAGCGC	CGTCACTTGGCGTATTGGTGTCTGATCTGTATCA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D7	GGTTATGCGGTTCACTGCTATAGAGCTCTACATA	CGTCACTTGGCGTATTGGGAGACTCTGTGCGCGT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D8	GGTTATGCGGTTCACTGCGCTGAGACGACGCGCG	CGTCACTTGGCGTATTGGCTCTCGTAGACAGATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D9	GGTTATGCGGTTCACTGCACGTAGTGCACACAGA	CGTCACTTGGCGTATTGGTGTGCACGACAGCAGT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D10	GGTTATGCGGTTCACTGCGATATATCGAGTATAT	CGTCACTTGGCGTATTGGTACATATGTCACGCGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D11	GGTTATGCGGTTCACTGCTGTCATGTGTACACAC	CGTCACTTGGCGTATTGGGTGAGTATGTACTCTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
D12	GGTTATGCGGTTCACTGCACATATCGTACTCTCT	CGTCACTTGGCGTATTGGGCGCAGTGTCACATCA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E1	GGTTATGCGGTTCACTGCACACGTGTGCTCTCTC	CGTCACTTGGCGTATTGGTGTCGTCTATCATGTA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E2	GGTTATGCGGTTCACTGCGATATACGCGAGAGAG	CGTCACTTGGCGTATTGGGCTGCGCTGATATGCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E3	GGTTATGCGGTTCACTGCCGTGTCTAGCGCGCGC	CGTCACTTGGCGTATTGGAGATATACTGTCTGAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E4	GGTTATGCGGTTCACTGCCGAGCATATATATCTC	CGTCACTTGGCGTATTGGACGTGAGCTCACTCGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E5	GGTTATGCGGTTCACTGCCTCACGTACGTCACAC	CGTCACTTGGCGTATTGGAGTAGACAGAGCGTGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E6	GGTTATGCGGTTCACTGCGCGCACGCACTACAGA	CGTCACTTGGCGTATTGGACACTGACGTCGCGAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E7	GGTTATGCGGTTCACTGCACGACATCGCTCACAG	CGTCACTTGGCGTATTGGTGACAGTATCACAGTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E8	GGTTATGCGGTTCACTGCAGACACACACGCACAT	CGTCACTTGGCGTATTGGTCGCTGACTCGACACA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E9	GGTTATGCGGTTCACTGCGACGAGCGTCTGAGAG	CGTCACTTGGCGTATTGGGCTCGCACAGCGCGTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E10	GGTTATGCGGTTCACTGCTGTGTCTCTGAGAGTA	CGTCACTTGGCGTATTGGGAGCTGATGTACATGT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E11	GGTTATGCGGTTCACTGCCACACGCACTGAGATA	CGTCACTTGGCGTATTGGTATGTGTCTGCGCATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
E12	GGTTATGCGGTTCACTGCGATGAGTATAGACACA	CGTCACTTGGCGTATTGGGCGCACAGACATCTGT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F1	GGTTATGCGGTTCACTGCGCTGTGTGTGCTCGTC	CGTCACTTGGCGTATTGGTGAGTGAGACATATCA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F2	GGTTATGCGGTTCACTGCTCTCAGATAGTCTATA	CGTCACTTGGCGTATTGGCATCGCGAGTGCGCTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F3	GGTTATGCGGTTCACTGCACACGCATGACACACT	CGTCACTTGGCGTATTGGTCATACACACAGATAG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F4	GGTTATGCGGTTCACTGCTATATACAGAGTCGAG	CGTCACTTGGCGTATTGGTAGCGTGAGAGTGTCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F5	GGTTATGCGGTTCACTGCGCGCTCTCTCACATAC	CGTCACTTGGCGTATTGGACAGTAGACTCTCAGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F6	GGTTATGCGGTTCACTGCTATATGCTCTGTGTGA	CGTCACTTGGCGTATTGGGTGACAGACGTCACGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F7	GGTTATGCGGTTCACTGCCTCTATATATCTCGTC	CGTCACTTGGCGTATTGGGTGACTCTATGCTATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F8	GGTTATGCGGTTCACTGCAGAGAGCTCTCTCATC	CGTCACTTGGCGTATTGGTCTGTCGATATACACT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F9	GGTTATGCGGTTCACTGCGCGAGAGTGAGACGCA	CGTCACTTGGCGTATTGGAGAGATGTGTGATGAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F10	GGTTATGCGGTTCACTGCTGCTCTCGTGTACTGT	CGTCACTTGGCGTATTGGCTGTGCTATGTACGCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F11	GGTTATGCGGTTCACTGCAGCGCTGCGACACGCG	CGTCACTTGGCGTATTGGCAGCGCATCTCACGTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
F12	GGTTATGCGGTTCACTGCAGACGCGAGCGCGTAG	CGTCACTTGGCGTATTGGGTGCAGTGATCGATGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G1	GGTTATGCGGTTCACTGCGCGTGTGTCGAGTGTA	CGTCACTTGGCGTATTGGGACACTCGCATGTGCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G2	GGTTATGCGGTTCACTGCTGTACGCTCTCTATAT	CGTCACTTGGCGTATTGGATATAGCGCATAGCTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G3	GGTTATGCGGTTCACTGCTATCTATCGCATATCG	CGTCACTTGGCGTATTGGGACTCTCTATCGTACT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G4	GGTTATGCGGTTCACTGCGTGCACTCGCGCTCTC	CGTCACTTGGCGTATTGGCGTGTCGCGCATATCT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G5	GGTTATGCGGTTCACTGCTCAGATGTGTCGCGAG	CGTCACTTGGCGTATTGGTACTAGAGTAGCACTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G6	GGTTATGCGGTTCACTGCCTCACACATACACGTC	CGTCACTTGGCGTATTGGCACTACTAGCGTGTGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G7	GGTTATGCGGTTCACTGCATAGTACACTCTGTGT	CGTCACTTGGCGTATTGGTACTCATATATGCTAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G8	GGTTATGCGGTTCACTGCTATCTCTGTAGAGTCT	CGTCACTTGGCGTATTGGAGACACGAGTCTAGAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G9	GGTTATGCGGTTCACTGCGATATATATGTGTGTA	CGTCACTTGGCGTATTGGTGTGTATCAGTACATG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G10	GGTTATGCGGTTCACTGCGTGACACACAGAGCAC	CGTCACTTGGCGTATTGGGTGCGCGAGAGTATAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G11	GGTTATGCGGTTCACTGCATATGACATACACGCA	CGTCACTTGGCGTATTGGAGCGACGCGAGAGTGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
G12	GGTTATGCGGTTCACTGCCGTCTCTCGTCTGTGC	CGTCACTTGGCGTATTGGGCGCTAGTGTGTACGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H1	GGTTATGCGGTTCACTGCACACAGTAGAGCGAGC	CGTCACTTGGCGTATTGGTGCATAGTAGTGCTCT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H2	GGTTATGCGGTTCACTGCTGACATCTACACATAC	CGTCACTTGGCGTATTGGTATCAGCACGACATGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H3	GGTTATGCGGTTCACTGCCTATCTAGCACTCACA	CGTCACTTGGCGTATTGGTACACACTATGTGCGT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H4	GGTTATGCGGTTCACTGCGTAGAGTGATCGCGTC	CGTCACTTGGCGTATTGGAGTCAGATGCGCACTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H5	GGTTATGCGGTTCACTGCCGCGCGAGTATCTCGT	CGTCACTTGGCGTATTGGGATACGAGAGCTGATG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H6	GGTTATGCGGTTCACTGCAGCACACATATAGCGC	CGTCACTTGGCGTATTGGCATCGTCACAGACATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H7	GGTTATGCGGTTCACTGCGTATATATATACGTCT	CGTCACTTGGCGTATTGGATAGAGAGTGTCTCAG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H8	GGTTATGCGGTTCACTGCATGAGTCTCACTGTAT	CGTCACTTGGCGTATTGGACATGCGTGACAGTCA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H9	GGTTATGCGGTTCACTGCTAGATGCGAGAGTAGA	CGTCACTTGGCGTATTGGCTCGTGACGCTGACTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H10	GGTTATGCGGTTCACTGCATAGCGACATCTCTCT	CGTCACTTGGCGTATTGGTGCGAGCGTGCACAGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H11	GGTTATGCGGTTCACTGCGCACGATGTCAGCGCG	CGTCACTTGGCGTATTGGCACATGTGACTCGACG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
H12	GGTTATGCGGTTCACTGCTGTGCTCTCTACACAG	CGTCACTTGGCGTATTGGTGTCTCGTGCTGAGAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T1	GGTTATGCGGTTCACTGCTGTATGAGTGTCTGAC	CGTCACTTGGCGTATTGGCAGCAGATCATGTCGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T2	GGTTATGCGGTTCACTGCCTCTGACTCGCGTCGA	CGTCACTTGGCGTATTGGCAGTGAGAGCGCGATA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T3	GGTTATGCGGTTCACTGCGACGACAGACTGCATA	CGTCACTTGGCGTATTGGCATCGTCTAGCACTCG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T4	GGTTATGCGGTTCACTGCGTGTAGCGTAGACAGT	CGTCACTTGGCGTATTGGTAGATCTATCATCGTC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T5	GGTTATGCGGTTCACTGCGACGTGTCGTAGATAT	CGTCACTTGGCGTATTGGGCACAGCGTAGCGCAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T6	GGTTATGCGGTTCACTGCCATGCTACGTCTCTGT	CGTCACTTGGCGTATTGGACGTCAGCACTGCTCT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T7	GGTTATGCGGTTCACTGCACTCTCGCTCTGTAGA	CGTCACTTGGCGTATTGGGACATAGCTAGATCGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T8	GGTTATGCGGTTCACTGCGCACTCAGAGACGCGA	CGTCACTTGGCGTATTGGGACTCGCGATACTAGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T9	GGTTATGCGGTTCACTGCACAGTATGATGTACTC	CGTCACTTGGCGTATTGGCGTGAGTATATGTCAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T10	GGTTATGCGGTTCACTGCGAGCTCATGTAGACAC	CGTCACTTGGCGTATTGGCGACTAGATCTATCAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T11	GGTTATGCGGTTCACTGCCTCTACATCAGTGCTA	CGTCACTTGGCGTATTGGATCGCATCGCAGAGAC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T12	GGTTATGCGGTTCACTGCAGATGTCATGTCTCTA	CGTCACTTGGCGTATTGGGTATAGACAGATGTGC	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T13	GGTTATGCGGTTCACTGCGTGAGAGTCTGATACT	CGTCACTTGGCGTATTGGGCGATCACTGTACACT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T14	GGTTATGCGGTTCACTGCGCGAGACTCAGCTCTG	CGTCACTTGGCGTATTGGACAGTCTATACTGCTG	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T15	GGTTATGCGGTTCACTGCTACATGTGTCTATGTC	CGTCACTTGGCGTATTGGACTGTGACAGTATGAT	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
T16	GGTTATGCGGTTCACTGCATCGTATAGTCATACA	CGTCACTTGGCGTATTGGACGTGCTCTATAGAGA	AGRRTTYGATYHTDGYTYAG	YCNTTCCYTYDYRGTACT
EOF

# Create default NP distribution
cat > mhass/resources/np_distribution.tsv << 'EOF'
2	19
3	23159
4	64526
5	81725
6	80698
7	77071
8	71763
9	66048
10	62179
11	58195
12	54959
13	51593
14	49300
15	46765
16	44700
17	42490
18	41828
19	39654
20	38867
21	37744
22	36815
23	36102
24	35995
25	35598
26	35348
27	35016
28	34766
29	33701
30	33645
31	32320
32	31418
33	30095
34	29630
35	28957
36	28577
37	27777
38	27618
39	27163
40	26759
41	25962
42	25473
43	23903
44	23211
45	21206
46	19972
47	18140
48	16593
49	14757
50	13718
51	12517
52	11510
53	10588
54	9817
55	8878
56	8489
57	7423
58	6983
59	7189
EOF


git clone https://github.com/rhowardstone/AmpliconHunter.git
cd AmpliconHunter
pip install -e .
cd ../

conda deactivate

#=====================
# Installation Complete
#=====================
log "All dependencies have been installed!"
log "You can now run the mhass command."
echo "=============================================="
echo "Installation of all dependencies completed!"
echo "=============================================="
echo "To use the simulator:"
echo "  1. Activate the conda environment:"
echo "     conda activate $ENV_NAME"
echo ""
echo "  2. Run the simulator:"
echo "     mhass --amplicon-fasta your_file.fa --amplicon-genome-labels your_labels.tsv --output-dir output/"
echo ""
echo "For detailed logs, check:"
echo "  - Installation log: $LOG_FILE"
echo ""
